#include "bongo_cat/model_plugin_host.h"
static SDL_Thread *host_create_thread(SDL_ThreadFunction fn, const char *name, void *data) {
    return SDL_CreateThread(fn, name, data);
}
static void *host_gl_proc(const char *name) {
    union { SDL_FunctionPointer function; void *pointer; } value;
    value.function = SDL_GL_GetProcAddress(name);
    return value.pointer;
}
static void host_log(int priority, const char *message) {
    SDL_LogMessage(SDL_LOG_CATEGORY_CUSTOM, (SDL_LogPriority)priority, "%s", message);
}
const BongoCatModelPluginHost *bongo_cat_model_plugin_host(void) {
    static const BongoCatModelPluginHost host = {
        .abi_version = BONGO_CAT_MODEL_PLUGIN_ABI,
        .struct_size = sizeof(BongoCatModelPluginHost),
        .core_symbol = bongo_cat_platform_live2d_core_symbol,
        .gl_proc = host_gl_proc,
        .log = host_log,
        .device_info = bongo_cat_rhi_get_active_device_info,
        .vulkan_frame = bongo_cat_rhi_get_vulkan_frame_info,
        .metal_frame = bongo_cat_rhi_get_metal_frame_info,
        .begin_commands = bongo_cat_rhi_begin_commands,
        .submit_commands = bongo_cat_rhi_submit_commands_checked,
        .wait_idle = bongo_cat_rhi_wait_idle,
        .SDL_CreateThread = host_create_thread,
        .SDL_Delay = SDL_Delay,
        .SDL_GL_GetCurrentContext = SDL_GL_GetCurrentContext,
        .SDL_GL_GetCurrentWindow = SDL_GL_GetCurrentWindow,
        .SDL_GetBasePath = SDL_GetBasePath,
        .SDL_GetPathInfo = SDL_GetPathInfo,
        .SDL_GetThreadState = SDL_GetThreadState,
        .SDL_GetTicksNS = SDL_GetTicksNS,
        .SDL_Log = SDL_Log,
        .SDL_LogDebug = SDL_LogDebug,
        .SDL_LogError = SDL_LogError,
        .SDL_LogInfo = SDL_LogInfo,
        .SDL_LogWarn = SDL_LogWarn,
        .SDL_WaitThread = SDL_WaitThread,
        .bongo_cat_error_set = bongo_cat_error_set,
        .bongo_cat_gl_clear_errors = bongo_cat_gl_clear_errors,
        .bongo_cat_image_forget_texture_cache = bongo_cat_image_forget_texture_cache,
        .bongo_cat_image_free = bongo_cat_image_free,
        .bongo_cat_image_info = bongo_cat_image_info,
        .bongo_cat_image_make_alpha_mask = bongo_cat_image_make_alpha_mask,
        .bongo_cat_image_resize_rgba_take = bongo_cat_image_resize_rgba_take,
        .bongo_cat_image_texture_job_cancel = bongo_cat_image_texture_job_cancel,
        .bongo_cat_image_texture_job_cleanup_poll = bongo_cat_image_texture_job_cleanup_poll,
        .bongo_cat_image_texture_job_destroy = bongo_cat_image_texture_job_destroy,
        .bongo_cat_image_texture_job_needs_poll = bongo_cat_image_texture_job_needs_poll,
        .bongo_cat_image_texture_job_poll = bongo_cat_image_texture_job_poll,
        .bongo_cat_image_texture_job_start = bongo_cat_image_texture_job_start,
        .bongo_cat_image_texture_model = bongo_cat_image_texture_model,
        .bongo_cat_image_texture_model_scaled_cached = bongo_cat_image_texture_model_scaled_cached,
        .bongo_cat_model_json_parse = bongo_cat_model_json_parse,
        .bongo_cat_model_memory_log = bongo_cat_model_memory_log,
        .bongo_cat_model_texture_mib = bongo_cat_model_texture_mib,
        .bongo_cat_platform_memory_usage = bongo_cat_platform_memory_usage,
        .bongo_cat_platform_trim_memory = bongo_cat_platform_trim_memory,
        .bongo_cat_resource_trace_atlas = bongo_cat_resource_trace_atlas,
        .bongo_cat_resource_trace_render = bongo_cat_resource_trace_render,
        .bongo_cat_rhi_active_is_gl = bongo_cat_rhi_active_is_gl,
        .bongo_cat_rhi_begin_commands = bongo_cat_rhi_begin_commands,
        .bongo_cat_rhi_get_active_device_info = bongo_cat_rhi_get_active_device_info,
        .bongo_cat_rhi_get_metal_frame_info = bongo_cat_rhi_get_metal_frame_info,
        .bongo_cat_rhi_get_vulkan_frame_info = bongo_cat_rhi_get_vulkan_frame_info,
        .bongo_cat_rhi_submit_commands_checked = bongo_cat_rhi_submit_commands_checked,
        .bongo_cat_rhi_wait_idle = bongo_cat_rhi_wait_idle,
        .bongo_cat_sha256_bytes = bongo_cat_sha256_bytes,
        .bongo_cat_sha256_file = bongo_cat_sha256_file,
        .bongo_safe_expression_parse = bongo_safe_expression_parse,
        .bongo_safe_free_expression = bongo_safe_free_expression,
        .bongo_safe_free_pixels = bongo_safe_free_pixels,
        .bongo_safe_image_decode = bongo_safe_image_decode,
        .bongo_json_arr_get = bongo_json_arr_get,
        .bongo_json_arr_size = bongo_json_arr_size,
        .bongo_json_doc_free = bongo_json_doc_free,
        .bongo_json_doc_get_root = bongo_json_doc_get_root,
        .bongo_json_free_text = bongo_json_free_text,
        .bongo_json_get_int = bongo_json_get_int,
        .bongo_json_get_num = bongo_json_get_num,
        .bongo_json_get_str = bongo_json_get_str,
        .bongo_json_is_arr = bongo_json_is_arr,
        .bongo_json_is_int = bongo_json_is_int,
        .bongo_json_is_num = bongo_json_is_num,
        .bongo_json_is_obj = bongo_json_is_obj,
        .bongo_json_is_str = bongo_json_is_str,
        .bongo_json_is_uint = bongo_json_is_uint,
        .bongo_json_obj_get = bongo_json_obj_get,
        .bongo_json_obj_key_at = bongo_json_obj_key_at,
        .bongo_json_obj_value_at = bongo_json_obj_value_at,
        .bongo_json_obj_size = bongo_json_obj_size,
        .bongo_json_read = bongo_json_read,
        .bongo_json_read_opts = bongo_json_read_opts,
        .bongo_json_write = bongo_json_write,
    };
    return &host;
}
