cmake_minimum_required(VERSION 3.24)
include("${CMAKE_CURRENT_LIST_DIR}/CubismVulkanRecording.cmake")
if(NOT DEFINED ROOT)
  get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
if(NOT DEFINED SDK OR SDK STREQUAL "")
  set(SDK "${ROOT}/vendor/CubismSdkForNative")
endif()
set(renderer "${SDK}/Framework/src/Rendering/Vulkan/CubismRenderer_Vulkan.cpp")
if(NOT EXISTS "${renderer}")
  message(STATUS "Cubism Vulkan recording check skipped: local SDK absent")
  return()
endif()
file(SHA256 "${renderer}" original_hash)
file(READ "${renderer}" original)
string(REPLACE "\r\n" "\n" original "${original}")
set(source "${original}")
if(MUTATION STREQUAL "missing")
  string(REPLACE "vkCmdBeginRendering(drawCommandBuffer, &renderingInfo);"
    "changed_sdk_rendering_call();" source "${source}")
elseif(MUTATION STREQUAL "ambiguous")
  set(binding "    BindVertexAndIndexBuffers(index, cmdBuffer, DrawableObjectType_Drawable);")
  string(REPLACE "${binding}" "${binding}\n${binding}" source "${source}")
endif()
bongo_cat_vulkan_recording_patch(source)
if(DEFINED MUTATION)
  message(FATAL_ERROR "Changed SDK was accepted: ${MUTATION}")
endif()

function(draw_function variable name output)
  string(FIND "${${variable}}" "void CubismRenderer_Vulkan::${name}(" begin)
  if(begin EQUAL -1)
    message(FATAL_ERROR "Function missing: ${name}")
  endif()
  string(SUBSTRING "${${variable}}" "${begin}" -1 tail)
  string(FIND "${tail}" "\nvoid CubismRenderer_Vulkan::" length)
  if(length EQUAL -1)
    message(FATAL_ERROR "Function boundary missing: ${name}")
  endif()
  string(SUBSTRING "${tail}" 0 "${length}" body)
  set(${output} "${body}" PARENT_SCOPE)
endfunction()
# Masks, advanced blending, descriptor writes and the SDK submission order
# must retain their original behavior outside the ordinary drawing hooks.
foreach(name IN ITEMS ExecuteDrawForMask ExecuteDrawForOffscreen
    ExecuteDrawForRenderTarget DoDrawModel DrawObjectLoop)
  draw_function(original "${name}" expected)
  draw_function(source "${name}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Recording changed the serial fallback: ${name}")
  endif()
endforeach()
foreach(gate IN ITEMS "!isResume" "!GetModel()->IsBlendModeEnabled()"
    "GetModel()->GetOffscreenCount() == 0" "!IsUsingHighPrecisionMask()"
    "GetModel()->GetDrawableCount() >= 128"
    "VK_RENDERING_CONTENTS_SECONDARY_COMMAND_BUFFERS_BIT"
    "bongo_cat::vulkan_recording_end(drawCommandBuffer);")
  string(FIND "${source}" "${gate}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "Recording compatibility guard missing: ${gate}")
  endif()
endforeach()
foreach(mutation IN ITEMS missing ambiguous)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DROOT=${ROOT}" "-DSDK=${SDK}"
    "-DMUTATION=${mutation}" -P "${CMAKE_CURRENT_LIST_FILE}"
    RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE error)
  if(result EQUAL 0 OR NOT error MATCHES "Cubism Vulkan recording patch")
    message(FATAL_ERROR "Recording SDK mismatch check failed: ${mutation}: ${error}")
  endif()
endforeach()
file(SHA256 "${renderer}" current_hash)
if(NOT current_hash STREQUAL original_hash)
  message(FATAL_ERROR "Recording patch modified the user SDK")
endif()
message(STATUS "Cubism Vulkan recording hooks, serial fallback and mismatch checks passed")
