cmake_minimum_required(VERSION 3.24)
include("${CMAKE_CURRENT_LIST_DIR}/WriteIfDifferent.cmake")
if(NOT DEFINED TEST_DIR)
  set(TEST_DIR "${CMAKE_CURRENT_LIST_DIR}/../build-review/generated-input-test")
endif()
file(MAKE_DIRECTORY "${TEST_DIR}")
set(output "${TEST_DIR}/stable.txt")
file(REMOVE "${output}")
# Preserve literal CMake placeholders and list separators in generated data.
set(content [=[alpha;beta
@untouched@ ${untouched}
]=])
bongo_cat_write_if_different("${output}" "${content}")
file(TIMESTAMP "${output}" before "%s")
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1)
bongo_cat_write_if_different("${output}" "${content}")
file(TIMESTAMP "${output}" after "%s")
file(READ "${output}" actual)
if(NOT before STREQUAL after OR NOT actual STREQUAL content)
  message(FATAL_ERROR "Unchanged generated input was rewritten or altered")
endif()
bongo_cat_write_if_different("${output}" "changed")
file(READ "${output}" actual)
if(NOT actual STREQUAL "changed")
  message(FATAL_ERROR "Changed generated input was not updated")
endif()
file(REMOVE "${output}")
message(STATUS "Generated input content and timestamp stability passed")
