cmake_minimum_required(VERSION 3.24)
include("${CMAKE_CURRENT_LIST_DIR}/CubismNativeShaderIO.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/CubismVulkanSafety.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/CubismVulkanBindless.cmake")
if(NOT DEFINED ROOT)
  get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
if(NOT DEFINED SDK OR SDK STREQUAL "")
  set(SDK "${ROOT}/vendor/CubismSdkForNative")
endif()
set(renderer "${SDK}/Framework/src/Rendering/Vulkan/CubismRenderer_Vulkan.cpp")
set(common "${SDK}/Framework/src/Rendering/Vulkan/Shaders/src/common.glsl")
if(NOT EXISTS "${renderer}" OR NOT EXISTS "${common}")
  message(STATUS "Cubism Vulkan Bindless check skipped: local SDK absent")
  return()
endif()
file(SHA256 "${renderer}" renderer_hash)
file(SHA256 "${common}" common_hash)
file(READ "${renderer}" source)
string(REPLACE "\r\n" "\n" source "${source}")
bongo_cat_vulkan_shader_io(source)
bongo_cat_harden_vulkan_pipelines(source)
bongo_cat_vulkan_recording_patch(source)
set(before "${source}")
bongo_cat_vulkan_bindless_patch(source)
file(READ "${common}" shader)
if(MUTATION STREQUAL "shader")
  string(REPLACE "sampler2D s_texture0" "sampler2D changed_texture" shader "${shader}")
endif()
bongo_cat_vulkan_bindless_common(shader)
if(DEFINED MUTATION)
  message(FATAL_ERROR "Changed SDK Bindless shader was accepted")
endif()
foreach(name IN ITEMS ExecuteDrawForOffscreen ExecuteDrawForRenderTarget UpdateDescriptorSetForOffscreen)
  set(prefix "void CubismRenderer_Vulkan::${name}(")
  foreach(variable IN ITEMS before source)
    string(FIND "${${variable}}" "${prefix}" start)
    string(SUBSTRING "${${variable}}" "${start}" -1 tail)
    string(FIND "${tail}" "\nvoid CubismRenderer_Vulkan::" length)
    string(SUBSTRING "${tail}" 0 "${length}" ${variable}_body)
  endforeach()
  if(NOT before_body STREQUAL source_body)
    message(FATAL_ERROR "Bindless changed advanced blend/offscreen fallback: ${name}")
  endif()
endforeach()
foreach(anchor IN ITEMS "file.insert(extension, \"_Bindless\");"
    "pipelineLayoutInfo.setLayoutCount = 2;" "pipelineLayoutInfo.pushConstantRangeCount = 1;"
    "bongo_cat::vulkan_bindless_bind(cmdBuffer, pipelineLayout, textureIndex);"
    "if (!bongo_cat::vulkan_bindless_active()) descriptorWrites.PushBack(image1);")
  string(FIND "${source}" "${anchor}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "Bindless renderer hook missing: ${anchor}")
  endif()
endforeach()
file(READ "${ROOT}/src/live2d/cubism_vulkan_bindless.hpp" header)
string(REGEX MATCH "vulkan_texture_table_capacity = ([0-9]+)" capacity "${header}")
set(size "${CMAKE_MATCH_1}")
string(FIND "${shader}" "bongo_atlases[${size}]" found)
if(found EQUAL -1)
  message(FATAL_ERROR "Bindless shader and host table capacities differ")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" "-DROOT=${ROOT}" "-DSDK=${SDK}"
  -DMUTATION=shader -P "${CMAKE_CURRENT_LIST_FILE}"
  RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE error)
if(result EQUAL 0 OR NOT error MATCHES "Cubism Vulkan recording patch mismatch")
  message(FATAL_ERROR "Bindless shader mismatch was not rejected: ${error}")
endif()
file(SHA256 "${renderer}" current_renderer)
file(SHA256 "${common}" current_common)
if(NOT renderer_hash STREQUAL current_renderer OR NOT common_hash STREQUAL current_common)
  message(FATAL_ERROR "Bindless patch modified the user SDK")
endif()
message(STATUS "Cubism Bindless hooks, shader capacity, fallback and mismatch checks passed")
