cmake_minimum_required(VERSION 3.24)
include("${CMAKE_CURRENT_LIST_DIR}/CubismVulkanVertexUpload.cmake")
if(NOT DEFINED SDK OR SDK STREQUAL "")
  get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
  set(SDK "${ROOT}/vendor/CubismSdkForNative")
endif()
set(renderer "${SDK}/Framework/src/Rendering/Vulkan/CubismRenderer_Vulkan.cpp")
if(NOT EXISTS "${renderer}")
  message(STATUS "Cubism Vulkan vertex upload check skipped: local SDK absent")
  return()
endif()
file(SHA256 "${renderer}" original_hash)
file(READ "${renderer}" source)
string(REPLACE "\r\n" "\n" source "${source}")
if(MUTATION STREQUAL "missing")
  string(REPLACE "vertices.PushBack(vertex);" "changed_sdk_upload();" source "${source}")
elseif(MUTATION STREQUAL "missing_pass")
  string(REPLACE "void CubismRenderer_Vulkan::DoDrawModel()"
    "void CubismRenderer_Vulkan::ChangedDrawModel()" source "${source}")
elseif(MUTATION STREQUAL "ambiguous")
  string(APPEND source "\n        vertices.PushBack(vertex);\n")
endif()
bongo_cat_vulkan_vertex_upload_patch(source)
foreach(required IN ITEMS "vulkan_buffer_mapped_data(" "if (!mapped) vertices.PrepareCapacity(vcount);"
    "if (vcount <= 0) return;" "if (mapped) std::memcpy(mapped +"
    "if (!mapped)\n        _stagingBuffers" "vkCmdCopyBuffer(commandBuffer,"
    "if (!_drawableClippingManager && !_offscreenClippingManager)"
    "DrawObjectLoop(updateCommandBuffer, drawCommandBuffer, beginInfo);\n        return;")
  string(FIND "${source}" "${required}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "Vertex upload behavior missing: ${required}")
  endif()
endforeach()
# Verify that the independent secondary-recording adaptation still composes.
include("${CMAKE_CURRENT_LIST_DIR}/CubismVulkanRecording.cmake")
bongo_cat_vulkan_recording_patch(source)
foreach(mutation IN ITEMS missing ambiguous missing_pass)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DSDK=${SDK}" "-DMUTATION=${mutation}"
    -P "${CMAKE_CURRENT_LIST_FILE}"
    RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE error)
  if(result EQUAL 0 OR NOT error MATCHES "Cubism Vulkan vertex upload patch")
    message(FATAL_ERROR "Vertex upload SDK mismatch check failed: ${mutation}: ${error}")
  endif()
endforeach()
file(SHA256 "${renderer}" current_hash)
if(NOT current_hash STREQUAL original_hash)
  message(FATAL_ERROR "Vertex upload patch modified the user SDK")
endif()
message(STATUS "Vulkan direct vertex upload, fallback and SDK mismatch checks passed")
