# Both SDK renderers require all 79 authored color/alpha blend combinations.
function(bongo_cat_compile_native_shaders backend input output)
  file(MAKE_DIRECTORY "${output}" "${CMAKE_BINARY_DIR}/native-shader-intermediates")
  if(backend STREQUAL "VULKAN")
    find_program(BONGO_CAT_GLSLANG_VALIDATOR NAMES glslangValidator glslang
      HINTS "$ENV{VULKAN_SDK}/Bin" "$ENV{VK_SDK_PATH}/Bin" REQUIRED)
    file(GLOB inputs "${input}/*.vert" "${input}/*.frag")
    file(GLOB includes "${input}/*.glsl")
    set(extension spv)
  else()
    find_program(xcrun NAMES xcrun REQUIRED)
    file(GLOB inputs "${input}/*.metal")
    list(FILTER inputs EXCLUDE REGEX "/(FragShaderSrcColorBlend|FragShaderSrcAlphaBlend)\\.metal$")
    file(GLOB includes "${input}/*.h" "${input}/*ColorBlend.metal" "${input}/*AlphaBlend.metal")
    set(extension metallib)
    if(CMAKE_OSX_DEPLOYMENT_TARGET)
      set(metal_target "-mmacosx-version-min=${CMAKE_OSX_DEPLOYMENT_TARGET}")
    endif()
  endif()
  set(colors Normal Add AddGlow Darken Multiply ColorBurn LinearBurn Lighten
    Screen ColorDodge Overlay SoftLight HardLight LinearLight Hue Color)
  set(alphas Over Atop Out ConjointOver DisjointOver)
  foreach(shader IN LISTS inputs)
    get_filename_component(stem "${shader}" NAME_WE)
    unset(_bongo_shader_preamble_args)
    unset(_bongo_preamble_dep)
    set(_bongo_compile_src "${shader}")
    if(backend STREQUAL "VULKAN")
      file(READ "${shader}" _bongo_shader_text)
      if(NOT _bongo_shader_text MATCHES "GL_GOOGLE_include_directive")
        # The SDK shaders normally enable #include themselves; if one does
        # not, inject the directive after #version (it is illegal before it)
        # into a generated source and add the original directory to the
        # include path so its relative #include lookups still resolve.
        get_filename_component(_bongo_shader_name "${shader}" NAME)
        set(_bongo_preamble_src
          "${CMAKE_BINARY_DIR}/native-shader-intermediates/preamble-${_bongo_shader_name}")
        string(FIND "${_bongo_shader_text}" "#version" _bongo_version_pos)
        if(_bongo_version_pos GREATER -1)
          string(FIND "${_bongo_shader_text}" "\n" _bongo_version_eol
            "${_bongo_version_pos}")
        else()
          set(_bongo_version_eol -1)
        endif()
        if(_bongo_version_pos GREATER -1 AND _bongo_version_eol GREATER -1)
          math(EXPR _bongo_version_end "${_bongo_version_eol} + 1")
          string(SUBSTRING "${_bongo_shader_text}" 0 "${_bongo_version_end}"
            _bongo_preambled)
          string(SUBSTRING "${_bongo_shader_text}" "${_bongo_version_end}" -1
            _bongo_shader_rest)
          string(APPEND _bongo_preambled
            "#extension GL_GOOGLE_include_directive : enable\n"
            "${_bongo_shader_rest}")
        else()
          set(_bongo_preambled
            "#extension GL_GOOGLE_include_directive : enable\n${_bongo_shader_text}")
        endif()
        file(WRITE "${_bongo_preamble_src}" "${_bongo_preambled}")
        set(_bongo_compile_src "${_bongo_preamble_src}")
        set(_bongo_preamble_dep "${_bongo_preamble_src}")
        list(APPEND _bongo_shader_preamble_args "-I${input}")
      endif()
    endif()
    set(variants "base")
    if(stem MATCHES "^Frag.*Blend$")
      set(variants "")
      foreach(color IN LISTS colors)
        foreach(alpha IN LISTS alphas)
          if(NOT (color STREQUAL "Normal" AND alpha STREQUAL "Over"))
            list(APPEND variants "${color}:${alpha}")
          endif()
        endforeach()
      endforeach()
    endif()
    foreach(variant IN LISTS variants)
      set(name "${stem}")
      set(defines "")
      if(NOT variant STREQUAL "base")
        string(REPLACE ":" ";" pair "${variant}")
        list(GET pair 0 color)
        list(GET pair 1 alpha)
        list(FIND colors "${color}" color_index)
        list(FIND alphas "${alpha}" alpha_index)
        set(name "${stem}${color}${alpha}")
        set(defines "-DCSM_COLOR_BLEND_MODE=${color_index}" "-DCSM_ALPHA_BLEND_MODE=${alpha_index}")
      endif()
      set(binary "${output}/${name}.${extension}")
      if(backend STREQUAL "VULKAN")
        add_custom_command(OUTPUT "${binary}"
          COMMAND "${BONGO_CAT_GLSLANG_VALIDATOR}" -V ${_bongo_shader_preamble_args} ${defines} "${_bongo_compile_src}" -o "${binary}"
          DEPENDS "${shader}" ${includes} ${_bongo_preamble_dep} VERBATIM)
      else()
        set(air "${CMAKE_BINARY_DIR}/native-shader-intermediates/${name}.air")
        add_custom_command(OUTPUT "${binary}"
          COMMAND "${xcrun}" -sdk macosx metal ${metal_target} ${defines} -c "${shader}" -o "${air}"
          COMMAND "${xcrun}" -sdk macosx metallib "${air}" -o "${binary}"
          DEPENDS "${shader}" ${includes} VERBATIM)
      endif()
      list(APPEND binaries "${binary}")
    endforeach()
  endforeach()
  string(TOLOWER "${backend}" suffix)
  add_custom_target(bongo_cat_${suffix}_shaders ALL DEPENDS ${binaries})
  add_dependencies(Framework bongo_cat_${suffix}_shaders)
  set(BONGO_CAT_${backend}_SHADER_BINARIES "${binaries}" PARENT_SCOPE)
endfunction()
