# Only included on macOS; SDK sources are copied/modified in build directories.
set(metal_dir "${CUBISM_FRAMEWORK_PATH}/src/Rendering/Metal")
set(metal_output "${CMAKE_BINARY_DIR}/cubism-renderer-metal")
file(MAKE_DIRECTORY "${metal_output}")
file(GLOB metal_sources "${metal_dir}/*.mm")
if(NOT metal_sources)
  message(FATAL_ERROR "The imported Cubism SDK has no Metal renderer")
endif()
set(original "${metal_dir}/CubismRenderer_Metal.mm")
file(READ "${original}" source)
string(REPLACE "\r\n" "\n" source "${source}")
foreach(factory IN ITEMS
    "CubismRenderer* CubismRenderer::Create(csmUint32 width, csmUint32 height)\n{\n    return CSM_NEW CubismRenderer_Metal(width, height);\n}\n"
    "void CubismRenderer::StaticRelease()\n{\n}\n")
  string(FIND "${source}" "${factory}" position)
  if(position EQUAL -1)
    message(FATAL_ERROR "Cubism Metal factory patch mismatch")
  endif()
  string(REPLACE "${factory}" "" source "${source}")
endforeach()
set(patched "${metal_output}/CubismRenderer_factory_Metal.mm")
file(WRITE "${patched}" "${source}")
list(REMOVE_ITEM metal_sources "${original}")
list(APPEND metal_sources "${patched}")
include(cmake/CubismNativeShaderIO.cmake)
set(shader_original "${metal_dir}/CubismShader_Metal.mm")
file(READ "${shader_original}" source)
bongo_cat_metal_shader_io(source)
set(shader_patched "${metal_output}/CubismShader_assets_Metal.mm")
file(WRITE "${shader_patched}" "${source}")
list(REMOVE_ITEM metal_sources "${shader_original}")
list(APPEND metal_sources "${shader_patched}")
set_source_files_properties(${metal_sources} PROPERTIES COMPILE_OPTIONS "-fno-objc-arc")
target_sources(Framework PRIVATE ${metal_sources})
target_include_directories(Framework SYSTEM PRIVATE "${metal_dir}")
target_link_libraries(Framework PUBLIC "-framework Metal" "-framework QuartzCore")

include(cmake/CubismNativeShaders.cmake)
bongo_cat_compile_native_shaders(METAL "${metal_dir}/Shaders"
  "${CMAKE_BINARY_DIR}/FrameworkMetallibs")
set(BONGO_CAT_METAL_SHADER_OUTPUT "${CMAKE_BINARY_DIR}/FrameworkMetallibs")
