# Both SDK renderers require all 79 authored color/alpha blend combinations.
function(bongo_cat_compile_native_shaders backend input output)
  file(MAKE_DIRECTORY "${output}" "${CMAKE_BINARY_DIR}/native-shader-intermediates")
  if(backend STREQUAL "VULKAN")
    find_program(BONGO_CAT_GLSLANG_VALIDATOR NAMES glslangValidator glslang
      HINTS "$ENV{VULKAN_SDK}/Bin" "$ENV{VK_SDK_PATH}/Bin" REQUIRED)
    file(GLOB inputs "${input}/*.vert" "${input}/*.frag")
    file(GLOB includes "${input}/*.glsl")
    set(extension spv)
  else()
    find_program(xcrun NAMES xcrun REQUIRED)
    file(GLOB inputs "${input}/*.metal")
    list(FILTER inputs EXCLUDE REGEX "/(FragShaderSrcColorBlend|FragShaderSrcAlphaBlend)\\.metal$")
    file(GLOB includes "${input}/*.h" "${input}/*ColorBlend.metal" "${input}/*AlphaBlend.metal")
    set(extension metallib)
    if(CMAKE_OSX_DEPLOYMENT_TARGET)
      set(metal_target "-mmacosx-version-min=${CMAKE_OSX_DEPLOYMENT_TARGET}")
    endif()
  endif()
  set(colors Normal Add AddGlow Darken Multiply ColorBurn LinearBurn Lighten
    Screen ColorDodge Overlay SoftLight HardLight LinearLight Hue Color)
  set(alphas Over Atop Out ConjointOver DisjointOver)
  foreach(shader IN LISTS inputs)
    get_filename_component(stem "${shader}" NAME_WE)
    set(variants "base")
    if(stem MATCHES "^Frag.*Blend$")
      set(variants "")
      foreach(color IN LISTS colors)
        foreach(alpha IN LISTS alphas)
          if(NOT (color STREQUAL "Normal" AND alpha STREQUAL "Over"))
            list(APPEND variants "${color}:${alpha}")
          endif()
        endforeach()
      endforeach()
    endif()
    foreach(variant IN LISTS variants)
      set(name "${stem}")
      set(defines "")
      if(NOT variant STREQUAL "base")
        string(REPLACE ":" ";" pair "${variant}")
        list(GET pair 0 color)
        list(GET pair 1 alpha)
        list(FIND colors "${color}" color_index)
        list(FIND alphas "${alpha}" alpha_index)
        set(name "${stem}${color}${alpha}")
        set(defines "-DCSM_COLOR_BLEND_MODE=${color_index}" "-DCSM_ALPHA_BLEND_MODE=${alpha_index}")
      endif()
      set(binary "${output}/${name}.${extension}")
      if(backend STREQUAL "VULKAN")
        add_custom_command(OUTPUT "${binary}"
          COMMAND "${BONGO_CAT_GLSLANG_VALIDATOR}" -V "--preamble-text" "#extension GL_GOOGLE_include_directive : enable" ${defines} "${shader}" -o "${binary}"
          DEPENDS "${shader}" ${includes} VERBATIM)
      else()
        set(air "${CMAKE_BINARY_DIR}/native-shader-intermediates/${name}.air")
        add_custom_command(OUTPUT "${binary}"
          COMMAND "${xcrun}" -sdk macosx metal ${metal_target} ${defines} -c "${shader}" -o "${air}"
          COMMAND "${xcrun}" -sdk macosx metallib "${air}" -o "${binary}"
          DEPENDS "${shader}" ${includes} VERBATIM)
      endif()
      list(APPEND binaries "${binary}")
    endforeach()
  endforeach()
  string(TOLOWER "${backend}" suffix)
  add_custom_target(bongo_cat_${suffix}_shaders ALL DEPENDS ${binaries})
  add_dependencies(Framework bongo_cat_${suffix}_shaders)
  set(BONGO_CAT_${backend}_SHADER_BINARIES "${binaries}" PARENT_SCOPE)
endfunction()
