# -*- coding: utf-8 -*-
"""Generate the Cubism Core runtime shim for plugin builds.

Runtime-Core builds never link the proprietary Core: the Cubism
Framework calls the csm* ABI, and this shim owns those symbols, forwarding
every call through host callbacks to the user-supplied shared library located at
runtime by the POSIX platform loader.

Declarations are parsed from the SDK's own Live2DCubismCore.h, so the shim
always matches the SDK version in vendor/CubismSdkForNative. Invoked from
cmake/Cubism.cmake:

    python cmake/gen_core_shim.py --header <Core>/include/Live2DCubismCore.h \
        --output <build>/generated/cubism_core_shim.c
"""
import argparse
import re
import sys

HEADER = """\
/* Generated by cmake/gen_core_shim.py from Live2DCubismCore.h; do not edit.
   The shim owns the csm* ABI in Runtime-Core builds and forwards every
   call to the user-supplied shared Core library located at runtime. */
#include "Live2DCubismCore.h"

#include "cubism_plugin_services.hpp"
#include <stddef.h>
"""

FOOTER = """\
static void *core_resolve(const char *name, void **slot) {
    if (!*slot) *slot = bongo_cat_model_plugin_host()->core_symbol(name);
    return *slot;
}
"""


def split_params(args):
    """Split a parameter list at top-level commas."""
    params, depth, current = [], 0, ""
    for character in args:
        if character == "(":
            depth += 1
        elif character == ")":
            depth -= 1
        if character == "," and depth == 0:
            params.append(current)
            current = ""
        else:
            current += character
    if current.strip():
        params.append(current)
    return params


def parse_declarations(text):
    """Extract (return type, name, parameters) for every csmApi declaration."""
    without_comments = re.sub(r"/\*.*?\*/", " ", text, flags=re.DOTALL)
    code_lines = [line for line in without_comments.split("\n")
                  if not line.strip().startswith("#")]
    flat = " ".join(line.strip() for line in code_lines)
    pattern = re.compile(
        r"\bcsmApi\s+(.+?)\s+csmCallingConvention\s+(csm\w+)\s*\(([^()]*)\)\s*;")
    declarations = []
    for match in pattern.finditer(flat):
        return_type, name, args = match.groups()
        declarations.append((return_type.strip(), name, args.strip()))
    if len(declarations) < 40:
        sys.exit("gen_core_shim.py: only %d Core declarations found; "
                 "the header format may have changed" % len(declarations))
    names = [name for _, name, _ in declarations]
    if len(names) != len(set(names)):
        sys.exit("gen_core_shim.py: duplicate Core declarations")
    return declarations


def parameter_list(args):
    """Return the parameters with synthetic names (p0, p1, ...)."""
    params = split_params(args)
    if not params or params[0].strip() in ("", "void"):
        return "void"
    named = []
    for index, param in enumerate(params):
        param = param.strip()
        tokens = param.split()
        if len(tokens) >= 2 and re.fullmatch(r"[A-Za-z_]\w*", tokens[-1]):
            param = " ".join(tokens[:-1] + ["p%d" % index])
        else:
            param = "%s p%d" % (param, index)
        named.append(param)
    return ", ".join(named)


def emit_function(return_type, name, args):
    signature = parameter_list(args)
    lines = []
    lines.append("csmApi %s csmCallingConvention %s(%s) {"
                 % (return_type, name, signature))
    lines.append("    static void *slot;")
    lines.append("    %s (csmCallingConvention *fn)(%s) = (%s (csmCallingConvention *)(%s))("
                 % (return_type, signature, return_type, signature))
    lines.append('        core_resolve("%s", &slot));' % name)
    if return_type != "void":
        lines.append("    return fn ? fn(%s) : (%s)0;"
                     % (call_arguments(signature), return_type))
    else:
        lines.append("    if (fn) fn(%s);" % call_arguments(signature))
    lines.append("}")
    return "\n".join(lines)


def call_arguments(signature):
    if signature == "void":
        return ""
    return ", ".join(
        part.split()[-1] for part in signature.split(", ") if part.strip())


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--header", required=True)
    parser.add_argument("--output", required=True)
    arguments = parser.parse_args()
    with open(arguments.header, encoding="utf-8") as handle:
        declarations = parse_declarations(handle.read())
    out = [HEADER, FOOTER, ""]
    out.append("/* Core ABI forwarders, in header declaration order. */")
    for return_type, name, args in declarations:
        out.append(emit_function(return_type, name, args))
        out.append("")
    body = "\n".join(out).rstrip() + "\n"
    with open(arguments.output, "wb") as handle:
        handle.write(body.replace("\n", "\r\n").encode("utf-8"))
    print("core shim generated; %d functions" % len(declarations))


if __name__ == "__main__":
    main()
